version: '3.0'

services:
  deer-radio-mysql:
    container_name: deer-radio-mysql
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '3301:3306'
    volumes:
      - deer-radio-mysql-data:/var/lib/mysql
    networks:
      - deer-radio-network
    healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u $$DB_USERNAME --password=$$DB_PASSWORD
        interval: 5s
        timeout: 5s
        retries: 55

  deer-radio-php-fpm:
    container_name: deer-radio-php-fpm
    build:
      context: ./
      dockerfile: .docker/php-fpm/Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/app:cached
      - deer-radio-app-data:/var/www/storage/app
      - deer-radio-php-vendor:/var/www/app/vendor/
      - deer-radio-js-vendor:/var/www/app/node_modules/
    networks:
      - deer-radio-network
    depends_on:
      deer-radio-mysql:
          condition: service_healthy
    healthcheck:
        test: php artisan db:show | grep -c "deer-radio-mysql" > /dev/null
        interval: 5s
        timeout: 5s
        retries: 55

  deer-radio-nginx:
    container_name: deer-radio-nginx
    build:
      context: ./
      dockerfile: ./.docker/nginx/Dockerfile
    ports:
      - '81:80'
    volumes:
      - ./:/var/www/app:cached
      - deer-radio-app-data:/var/www/storage/app
      - deer-radio-php-vendor:/var/www/app/vendor/
      - deer-radio-js-vendor:/var/www/app/node_modules/
    networks:
      - deer-radio-network
    depends_on:
      deer-radio-php-fpm:
          condition: service_healthy
      deer-radio-mysql:
          condition: service_healthy

networks:
  deer-radio-network:
    driver: bridge

volumes:
  deer-radio-mysql-data:
    driver: local
  deer-radio-app-data:
    driver: local
  deer-radio-php-vendor:
    driver: local
  deer-radio-js-vendor:
    driver: local
